services:
  - type: web
    name: rakib-portfolio
    runtime: python
    pythonVersion: 3.11
    buildCommand: pip cache purge && pip install --no-cache-dir -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: GEMINI_API_KEY
        sync: false
      - key: SECRET_KEY
        generateValue: true
